name: JON

on:
    push:
        branches:
        - main
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
    workflow_dispatch:

env:
  DOJO_VERSION: v1.7.0
  SCARB_VERSION: v2.12.2

jobs:
  check:
    runs-on: ubuntu-latest
    name: Format
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - name: Format
        run: scarb fmt --check
        shell: bash

  build:
    runs-on: ubuntu-latest
    name: Build
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - uses: asdf-vm/actions/setup@v4
      - run: |
          asdf plugin add sozo https://github.com/dojoengine/asdf-sozo.git
          asdf install
          sozo build
          if [[ `git status --porcelain` ]]; then
            echo The git repo is dirty
            echo "Make sure to run \"sozo build\" after changing Scarb.toml and commit Scarb.lock"
            exit 1
          fi
