name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  sozo-test:
    runs-on: ubuntu-latest
    env:
      DOJO_VERSION: v1.5.0-alpha.2
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.10.1"
      - run: |
          curl -L https://install.dojoengine.org | bash
          /home/runner/.config/.dojo/dojoup/dojoup install ${{ env.DOJO_VERSION }}
      - run: |
          /home/runner/.config/.dojo/bin/sozo build
          /home/runner/.config/.dojo/bin/sozo test
          if [[ `git status --porcelain` ]]; then
            echo The git repo is dirty
            echo "Make sure to run \"sozo build\" after changing Scarb.toml and commit Scarb.lock"
            exit 1
          fi
